edition = "2024"
unstable_features = true

use_small_heuristics = "Max"
newline_style = "Unix"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
use_field_init_shorthand = true
use_try_shorthand = true
condense_wildcard_suffixes = true
normalize_comments = true
normalize_doc_attributes = true